"""Tests for ``sdk_compat`` — the Python port of the SDK transcript +
DLEQ + Schnorr + ballot pipeline.

Cross-impl interop fixtures in ``fixtures/`` were generated by the
shutter-voting-sdk directly (see ``scripts/sdk-fixtures/``). Loading
them here ensures our Python port produces and verifies the *same*
bytes the TypeScript SDK does.
"""

import json
from pathlib import Path

import pytest

from crypto.primitives import (
    G2,
    g1_from_compressed,
    g1_to_compressed,
    g2_from_compressed,
    g2_to_compressed,
    point_multiply,
    random_scalar,
)
from sdk_compat import (
    DLEQ_BYTES,
    Transcript,
    build_ballot,
    canonical_ballot_message,
    decode_dleq,
    decode_schnorr,
    encode_dleq,
    encode_schnorr,
    make_decryption_share,
    make_wr_attestation_verifier,
    prove_decryption_share,
    schnorr_keygen,
    schnorr_sign,
    schnorr_verify,
    verify_ballot,
    verify_decryption_share,
)


_FIXTURE_DIR = Path(__file__).resolve().parents[2] / "fixtures" / "decrypt-share"
_BALLOT_FIXTURE = (
    Path(__file__).resolve().parents[2]
    / "fixtures" / "ballot" / "ballot_variantA_exact_known.json"
)
_SCHNORR_FIXTURE = (
    Path(__file__).resolve().parents[2]
    / "fixtures" / "schnorr" / "schnorr_known_sk_k.json"
)


def _load_fixture(name: str) -> dict:
    return json.loads((_FIXTURE_DIR / f"{name}.json").read_text())


# ----------------------------------------------------------------------
#  DLEQ encoding
# ----------------------------------------------------------------------

def test_dleq_roundtrip():
    e = random_scalar()
    z = random_scalar()
    b = encode_dleq(e, z)
    assert len(b) == DLEQ_BYTES == 64
    e2, z2 = decode_dleq(b)
    assert (e2, z2) == (e, z)


def test_dleq_decode_wrong_length():
    with pytest.raises(ValueError, match="64-byte"):
        decode_dleq(b"\x00" * 63)


# ----------------------------------------------------------------------
#  Cross-impl fixtures (frozen, SDK-verified)
# ----------------------------------------------------------------------

@pytest.mark.parametrize("kid", [1, 2, 3])
def test_verify_existing_fixture(kid: int):
    """Our verifier must accept the bytes the SDK already accepts."""
    fix = _load_fixture(f"thresholdElGamal_dkg_keyper_{kid}")
    inp = fix["inputs"]

    C1 = g2_from_compressed(bytes.fromhex(inp["ct_sum"]["c1"]))
    C2 = g2_from_compressed(bytes.fromhex(inp["ct_sum"]["c2"]))
    mpk_k = g2_from_compressed(bytes.fromhex(inp["committee_pk"]))
    sigma = g2_from_compressed(bytes.fromhex(inp["share"]["sigma"]))
    e, z = decode_dleq(bytes.fromhex(inp["share"]["dleq_proof"]))

    t = Transcript(inp["transcript_label"])
    assert verify_decryption_share(
        t, C1, C2, mpk_k, sigma, e, z,
        keyper_index=inp["keyper_index"],
    )


# ----------------------------------------------------------------------
#  Self-consistency: prove → verify under the same transcript label
# ----------------------------------------------------------------------

def _setup_one_keyper():
    """Build a (mpk_k, msk_k, ciphertext) tuple for prover/verifier tests."""
    msk_k = random_scalar()
    mpk_k = point_multiply(G2, msk_k)
    r = random_scalar()
    plaintext = 5
    C1 = point_multiply(G2, r)
    C2 = point_multiply(mpk_k, r) + point_multiply(G2, plaintext)
    return msk_k, mpk_k, C1, C2


def test_prove_and_verify_self():
    msk_k, mpk_k, C1, C2 = _setup_one_keyper()
    sigma = point_multiply(C1, msk_k)

    tp = Transcript("test:label:1")
    e, z = prove_decryption_share(tp, C1, C2, mpk_k, sigma, msk_k, keyper_index=1)

    tv = Transcript("test:label:1")
    assert verify_decryption_share(tv, C1, C2, mpk_k, sigma, e, z, keyper_index=1)


def test_make_decryption_share_helper():
    msk_k, mpk_k, C1, C2 = _setup_one_keyper()
    sigma_bytes, (e, z) = make_decryption_share(
        C1, C2, mpk_k, msk_k, keyper_index=2,
        transcript_label="test:label:2",
    )

    sigma = g2_from_compressed(sigma_bytes)
    tv = Transcript("test:label:2")
    assert verify_decryption_share(tv, C1, C2, mpk_k, sigma, e, z, keyper_index=2)


# ----------------------------------------------------------------------
#  Soundness: tampering breaks verification
# ----------------------------------------------------------------------

def test_wrong_label_rejects():
    msk_k, mpk_k, C1, C2 = _setup_one_keyper()
    sigma_bytes, (e, z) = make_decryption_share(
        C1, C2, mpk_k, msk_k, keyper_index=1,
        transcript_label="bound:label",
    )
    sigma = g2_from_compressed(sigma_bytes)

    tv = Transcript("different:label")
    assert not verify_decryption_share(tv, C1, C2, mpk_k, sigma, e, z, keyper_index=1)


def test_wrong_keyper_index_rejects():
    msk_k, mpk_k, C1, C2 = _setup_one_keyper()
    sigma_bytes, (e, z) = make_decryption_share(
        C1, C2, mpk_k, msk_k, keyper_index=1,
        transcript_label="test",
    )
    sigma = g2_from_compressed(sigma_bytes)

    tv = Transcript("test")
    assert not verify_decryption_share(tv, C1, C2, mpk_k, sigma, e, z, keyper_index=2)


def test_tampered_sigma_rejects():
    msk_k, mpk_k, C1, C2 = _setup_one_keyper()
    sigma_bytes, (e, z) = make_decryption_share(
        C1, C2, mpk_k, msk_k, keyper_index=1,
        transcript_label="test",
    )
    sigma = g2_from_compressed(sigma_bytes)
    bad_sigma = sigma + G2  # different point in subgroup

    tv = Transcript("test")
    assert not verify_decryption_share(tv, C1, C2, mpk_k, bad_sigma, e, z, keyper_index=1)


def test_tampered_z_rejects():
    msk_k, mpk_k, C1, C2 = _setup_one_keyper()
    sigma_bytes, (e, z) = make_decryption_share(
        C1, C2, mpk_k, msk_k, keyper_index=1,
        transcript_label="test",
    )
    sigma = g2_from_compressed(sigma_bytes)

    tv = Transcript("test")
    assert not verify_decryption_share(tv, C1, C2, mpk_k, sigma, e, z + 1, keyper_index=1)


# ----------------------------------------------------------------------
#  Schnorr — cross-impl fixture (fixed sk and k from the SDK)
# ----------------------------------------------------------------------

def _load_schnorr_fixture() -> dict:
    return json.loads(_SCHNORR_FIXTURE.read_text())


def test_schnorr_keygen_matches_sdk():
    fix = _load_schnorr_fixture()["inputs"]
    sk_in = int(fix["sk"], 16)
    sk_out, vk = schnorr_keygen(sk_in)
    assert sk_out == sk_in
    assert g1_to_compressed(vk) == bytes.fromhex(fix["vk"])


def test_schnorr_sign_matches_sdk_byte_for_byte():
    """Pinned (sk, k, msg) → must produce identical (R, s) bytes."""
    fix = _load_schnorr_fixture()["inputs"]
    sk = int(fix["sk"], 16)
    k = int(fix["k"], 16)
    msg = bytes.fromhex(fix["message"])
    _, vk = schnorr_keygen(sk)
    R, s = schnorr_sign(sk, vk, msg, k=k)
    assert g1_to_compressed(R) == bytes.fromhex(fix["R"])
    assert s == int(fix["s"], 16)
    assert encode_schnorr(R, s) == bytes.fromhex(fix["sig_encoded"])


def test_schnorr_verify_accepts_sdk_signature():
    fix = _load_schnorr_fixture()["inputs"]
    vk = g1_from_compressed(bytes.fromhex(fix["vk"]))
    msg = bytes.fromhex(fix["message"])
    R, s = decode_schnorr(bytes.fromhex(fix["sig_encoded"]))
    assert schnorr_verify(vk, msg, R, s)


def test_schnorr_tampered_message_rejected():
    fix = _load_schnorr_fixture()["inputs"]
    vk = g1_from_compressed(bytes.fromhex(fix["vk"]))
    msg = bytes.fromhex(fix["message"])
    R, s = decode_schnorr(bytes.fromhex(fix["sig_encoded"]))
    assert not schnorr_verify(vk, msg + b"\x00", R, s)


def test_schnorr_tampered_s_rejected():
    fix = _load_schnorr_fixture()["inputs"]
    vk = g1_from_compressed(bytes.fromhex(fix["vk"]))
    msg = bytes.fromhex(fix["message"])
    R, s = decode_schnorr(bytes.fromhex(fix["sig_encoded"]))
    assert not schnorr_verify(vk, msg, R, (s + 1) % (1 << 255))


# ----------------------------------------------------------------------
#  Ballot pipeline — cross-impl fixture (full Variant-A / exact ballot)
# ----------------------------------------------------------------------

def _load_ballot_fixture() -> dict:
    return json.loads(_BALLOT_FIXTURE.read_text())


def _ballot_inputs():
    fix = _load_ballot_fixture()
    inp = fix["inputs"]
    return {
        "election_id": bytes.fromhex(inp["electionId"]),
        "pseudonym": bytes.fromhex(inp["pseudonym"]),
        "sk": int(inp["sk"], 16),
        "k": int(inp["k"], 16),
        "mpk_secret": int(inp["mpk_secret"], 16),
        "mpk_bytes": bytes.fromhex(inp["mpk"]),
        "vk_bytes": bytes.fromhex(inp["vk"]),
        "votes": [int(v) for v in inp["votes"]],
        "rs": [int(r, 16) for r in inp["randomness"]],
        "range_w": [int(w, 16) for w in inp["range_proof_w"]],
        "range_sims": [
            [None if s is None else (int(s["e"], 16), int(s["z"], 16)) for s in row]
            for row in inp["range_proof_sims"]
        ],
        "budget_w": int(inp["budget_proof_w"], 16),
        "params": inp["params"],
        "out": fix["outputs"],
    }


def test_build_ballot_matches_sdk_byte_for_byte():
    """Pinned (sk, k, mpk-msk, r_j, OR commits) → identical SDK ballot bytes.

    This is the cross-impl gold for the full voter pipeline: ciphertexts,
    1611-byte zkProof, canonical preimage, and 80-byte voterSignature must
    all match what shutter-voting-sdk's buildBallot produced.
    """
    f = _ballot_inputs()
    mpk = point_multiply(G2, f["mpk_secret"])
    assert g2_to_compressed(mpk) == f["mpk_bytes"]

    _, vk = schnorr_keygen(f["sk"])
    assert g1_to_compressed(vk) == f["vk_bytes"]

    result = build_ballot(
        mpk=mpk,
        election_id=f["election_id"], pseudonym=f["pseudonym"],
        sk=f["sk"], vk=vk, votes=f["votes"],
        num_candidates=f["params"]["numCandidates"], budget=f["params"]["budget"],
        rs=f["rs"], range_proof_w=f["range_w"], range_proof_sims=f["range_sims"],
        budget_proof_w=f["budget_w"], schnorr_k=f["k"],
    )

    expected_cts = [(bytes.fromhex(c1), bytes.fromhex(c2))
                    for c1, c2 in f["out"]["ciphertexts"]]
    assert result.ciphertexts == expected_cts
    assert result.zk_proof == bytes.fromhex(f["out"]["zkProof"])
    assert result.canonical_preimage == bytes.fromhex(f["out"]["canonical_preimage"])
    assert result.voter_signature == bytes.fromhex(f["out"]["voterSignature"])


def test_verify_ballot_accepts_sdk_ballot():
    f = _ballot_inputs()
    mpk = point_multiply(G2, f["mpk_secret"])
    ok, reason = verify_ballot(
        mpk=mpk,
        election_id=f["election_id"], pseudonym=f["pseudonym"],
        vk_bytes=f["vk_bytes"],
        ciphertext_bytes=[(bytes.fromhex(c1), bytes.fromhex(c2))
                          for c1, c2 in f["out"]["ciphertexts"]],
        zk_proof=bytes.fromhex(f["out"]["zkProof"]),
        voter_signature=bytes.fromhex(f["out"]["voterSignature"]),
        wr_attestation=b"",
        num_candidates=f["params"]["numCandidates"],
        budget=f["params"]["budget"],
        verify_wr=lambda *a: True,
    )
    assert ok, reason


def test_verify_ballot_rejects_tampered_ciphertext():
    f = _ballot_inputs()
    mpk = point_multiply(G2, f["mpk_secret"])
    # Replace ciphertext[0].c1 with a fresh point — proof transcript breaks.
    cts = [(bytes.fromhex(c1), bytes.fromhex(c2))
           for c1, c2 in f["out"]["ciphertexts"]]
    other = g2_to_compressed(point_multiply(G2, random_scalar()))
    cts[0] = (other, cts[0][1])
    ok, reason = verify_ballot(
        mpk=mpk,
        election_id=f["election_id"], pseudonym=f["pseudonym"],
        vk_bytes=f["vk_bytes"],
        ciphertext_bytes=cts,
        zk_proof=bytes.fromhex(f["out"]["zkProof"]),
        voter_signature=bytes.fromhex(f["out"]["voterSignature"]),
        wr_attestation=b"",
        num_candidates=f["params"]["numCandidates"],
        budget=f["params"]["budget"],
        verify_wr=lambda *a: True,
    )
    assert not ok
    assert reason is not None and ("range proof" in reason or "signature" in reason)


def test_verify_ballot_rejects_when_wr_attestation_fails():
    f = _ballot_inputs()
    mpk = point_multiply(G2, f["mpk_secret"])
    ok, reason = verify_ballot(
        mpk=mpk,
        election_id=f["election_id"], pseudonym=f["pseudonym"],
        vk_bytes=f["vk_bytes"],
        ciphertext_bytes=[(bytes.fromhex(c1), bytes.fromhex(c2))
                          for c1, c2 in f["out"]["ciphertexts"]],
        zk_proof=bytes.fromhex(f["out"]["zkProof"]),
        voter_signature=bytes.fromhex(f["out"]["voterSignature"]),
        wr_attestation=b"\x00",
        num_candidates=f["params"]["numCandidates"],
        budget=f["params"]["budget"],
        verify_wr=lambda *a: False,    # always rejects
    )
    assert not ok
    assert reason == "wrAttestation verification failed"


# ----------------------------------------------------------------------
#  WR attestation verifier (the dev oracle scheme)
# ----------------------------------------------------------------------

def test_wr_attestation_verifier_accepts_oracle_signature():
    """End-to-end: oracle signs → verifier built from pkWR accepts."""
    from wr_oracle import issue_attestation
    wr_sk, wr_vk = schnorr_keygen()
    pk_wr = g1_to_compressed(wr_vk)
    election_id = b"\x01" * 32
    pseudonym = b"\x02" * 32
    voter_vk = b"\x03" * 48

    attest = issue_attestation(wr_sk, wr_vk, election_id, pseudonym, voter_vk)
    verify_wr = make_wr_attestation_verifier(pk_wr)
    assert verify_wr(election_id, pseudonym, voter_vk, attest)


def test_wr_attestation_verifier_rejects_tampered_attestation():
    from wr_oracle import issue_attestation
    wr_sk, wr_vk = schnorr_keygen()
    pk_wr = g1_to_compressed(wr_vk)
    election_id = b"\x01" * 32
    pseudonym = b"\x02" * 32
    voter_vk = b"\x03" * 48

    attest = bytearray(issue_attestation(wr_sk, wr_vk, election_id, pseudonym, voter_vk))
    attest[10] ^= 0xFF
    verify_wr = make_wr_attestation_verifier(pk_wr)
    assert not verify_wr(election_id, pseudonym, voter_vk, bytes(attest))


def test_wr_attestation_verifier_rejects_wrong_voter_vk():
    """A WR attestation issued for vk_A must not validate against vk_B."""
    from wr_oracle import issue_attestation
    wr_sk, wr_vk = schnorr_keygen()
    pk_wr = g1_to_compressed(wr_vk)
    election_id = b"\x01" * 32
    pseudonym = b"\x02" * 32

    attest = issue_attestation(wr_sk, wr_vk, election_id, pseudonym, b"\x03" * 48)
    verify_wr = make_wr_attestation_verifier(pk_wr)
    assert not verify_wr(election_id, pseudonym, b"\x04" * 48, attest)
