#!/usr/bin/env python3
"""Render docker-compose.yml for the keyper + tally aggregator cluster.

Reads NUM_KEYPERS (and friends) from ``docker/.env`` and writes a compose
file with one service per keyper plus the tally aggregator. The compose
file is regenerated from scratch on every run, so the source of truth is
``.env`` — edit it and re-run this script before ``docker compose up``.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
ENV_FILE = HERE / ".env"
OUT_FILE = HERE / "docker-compose.yml"


def load_env(path: Path) -> dict[str, str]:
    if not path.exists():
        sys.exit(
            f"error: {path} not found — copy .env.example to .env and edit it first"
        )
    env: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip()
    return env


def require(env: dict[str, str], key: str) -> str:
    val = env.get(key)
    if val is None or val == "":
        sys.exit(f"error: {key} missing from .env")
    return val


def main() -> int:
    env = load_env(ENV_FILE)
    num = int(require(env, "NUM_KEYPERS"))
    if num < 1:
        sys.exit("error: NUM_KEYPERS must be >= 1")
    port_base = int(env.get("KEYPER_HOST_PORT_BASE", "5000"))

    for i in range(1, num + 1):
        require(env, f"KEYPER_PRIVATE_KEY_{i}")
    require(env, "TALLY_AGGREGATOR_PRIVATE_KEY")
    require(env, "RPC_URL")
    require(env, "ELECTION_ADDRESS")
    require(env, "ELECTION_ID")
    require(env, "DKG_THRESHOLD")

    keyper_urls = ",".join(f"http://keyper-{i}:5000" for i in range(1, num + 1))

    lines: list[str] = []
    lines.append("# Generated by generate-compose.py — edit .env, then re-run that script.")
    lines.append("services:")

    for i in range(1, num + 1):
        host_port = port_base + i
        lines.extend([
            f"  keyper-{i}:",
            "    build:",
            "      context: ..",
            "      dockerfile: docker/Dockerfile",
            "    image: threshold-elgamal-app",
            f"    container_name: keyper-{i}",
            "    environment:",
            f"      KEYPER_PRIVATE_KEY: ${{KEYPER_PRIVATE_KEY_{i}}}",
            "    command:",
            "      - python",
            "      - keyper.py",
            f"      - --id={i}",
            "      - --port=5000",
            "      - --host=0.0.0.0",
            "      - --rpc-url=${RPC_URL}",
            "    ports:",
            f'      - "{host_port}:5000"',
            "    extra_hosts:",
            '      - "host.docker.internal:host-gateway"',
            "    restart: unless-stopped",
            "",
        ])

    lines.extend([
        "  dkg-coordinator:",
        "    build:",
        "      context: ..",
        "      dockerfile: docker/Dockerfile",
        "    image: threshold-elgamal-app",
        "    container_name: dkg-coordinator",
        "    environment:",
        f'      KEYPER_URLS: "{keyper_urls}"',
        "      RPC_URL: ${RPC_URL}",
        "      ELECTION_ADDRESS: ${ELECTION_ADDRESS}",
        "      ELECTION_ID: ${ELECTION_ID}",
        f"      NUM_KEYPERS: \"{num}\"",
        "      DKG_THRESHOLD: ${DKG_THRESHOLD}",
        "    command: [\"dkg-runner\"]",
        "    extra_hosts:",
        '      - "host.docker.internal:host-gateway"',
        '    restart: "no"',
        "    depends_on:",
    ])
    for i in range(1, num + 1):
        lines.append(f"      - keyper-{i}")
    lines.append("")

    lines.extend([
        "  tally-aggregator:",
        "    build:",
        "      context: ..",
        "      dockerfile: docker/Dockerfile",
        "    image: threshold-elgamal-app",
        "    container_name: tally-aggregator",
        "    environment:",
        "      TALLY_AGGREGATOR_PRIVATE_KEY: ${TALLY_AGGREGATOR_PRIVATE_KEY}",
        "    command:",
        "      - python",
        "      - tally_aggregator.py",
        "      - daemon",
        "      - --rpc-url=${RPC_URL}",
        "      - --election=${ELECTION_ADDRESS}",
        "      - --poll=${TALLY_POLL_SECONDS:-10}",
        "    extra_hosts:",
        '      - "host.docker.internal:host-gateway"',
        "    restart: on-failure",
        "    depends_on:",
    ])
    for i in range(1, num + 1):
        lines.append(f"      - keyper-{i}")
    lines.append("")

    OUT_FILE.write_text("\n".join(lines))
    print(f"wrote {OUT_FILE} ({num} keypers, host ports {port_base + 1}..{port_base + num})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
